server:
  port: 8080

spring:
  graphql:
    graphiql.enabled: true
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:test_db
    username: admin
    password: Password@123
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect